---
title: "visualize isd"
author: "Colby Wilkinson"
date: "11/3/2019"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

Reading in data

```{r}
isd_data <- data.table::fread("../../data/final/ISD HOURLY.csv")
```

Scatter plot of hourly precipitation from 1999-2019, by City

```{r, dpi=100, fig.width=6, fig.height=10}
isd_data %>% 
  mutate(date = ymd_h(paste(year, month, day, hour, sep = " "))) %>% 
  ggplot(aes(x = date, y = prec_1)) +
  geom_line(color="steelblue4") +
  facet_wrap(~city, nrow = 4) +
  theme(axis.text = element_text(size = 10)) +
  theme(strip.text = element_text(size = 16)) +
  theme(axis.title = element_text(size = 15)) +
  ylab("Hourly Precipitation (inches)") +
  xlab("") +
  theme(axis.text.x=element_text(angle=60, hjust=1)) +
  ggsave("../../plots/prec_by_city.jpeg", dpi = 200, width = 10, height = 6, units = "in")
```

Boxplot of hourly precipitation by month for Boston

```{r}
isd_data %>% 
  filter(city == "Boston" & !is.na(month)) %>% 
  arrange(-month) %>% 
  mutate(month = as.character(month)) %>% 
  group_by(year, month) %>% 
  summarise(prec_month = sum(prec_1, na.rm = TRUE)) %>% 
  ggplot(aes(x = month, y = prec_month)) +
  geom_boxplot() +
  ggsave("../../plots/boston_prec_month.jpeg", width = 5, height = 3, units = "in", dpi = 200)
```

Monthly precipitation by city in 2015

```{r}
isd_data %>% 
  filter(year == 2015) %>% 
  group_by(city, month) %>% 
  summarise(prec = sum(prec_1, na.rm = TRUE)) %>% 
  ggplot(aes(x = month, y = prec, col = city)) +
  geom_line() +
  geom_point() +
  xlab("Month") +
  ylab("Precipitation") +
  ggtitle("Monthly Precipitation by City in 2015") +
  theme(plot.title = element_text(hjust = 0.5, size = 14)) + 
  scale_colour_discrete(name = "") +
  scale_x_continuous(breaks = 1:12, labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))
  
```

